### PR TITLE
Added better duck typing to distinguish actions

### PR DESCRIPTION
**Pull request by AmasaDelano**

### CODE REVIEW

**Comment by seiyria** [comment]
Do you think it makes sense to add an ActionType enum that has all of the action types, and assigning one to each action (even if it's not needed right now)? That might be good for future maintainability.

**Comment by AmasaDelano** [comment]
Sure, I'll add one and use it for the `type` fields.

**Comment by AmasaDelano** [comment]
There you go. :)

**Comment by seiyria** [comment]
published as 1.3.0!

**Pull request merged**
